language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
install:
- git submodule update --init --recursive
script:
- sbt ++$TRAVIS_SCALA_VERSION run
